import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenu from "@/components/nav-menu";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, "flex min-h-screen")}>
        <NavMenu />
        <main className=" bg-green-100 dark:bg-green-950 flex flex-col flex-1 px-5 py-2 relative gap-4 dar">
          {children}
        </main>
      </body>
    </html>
  );
}
